name: Run RDP server with ngrok

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install xrdp and configure RDP
      run: |
        sudo apt update
        sudo apt install -y xrdp
        sudo apt install -y xorgxrdp
        echo xfce4-session > ~/.xsession
        sudo service xrdp restart
        sudo adduser rdpuser --gecos "" --disabled-password
        echo "rdpuser:password" | sudo chpasswd

    - name: Set up noVNC and ngrok
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install novnc
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip

    - name: Start noVNC server
      run: |
        cd $GITHUB_WORKSPACE
        npx --no-install novnc --listen 8080 &

    - name: Expose port 3389 (RDP) with ngrok
      run: |
        ./ngrok authtoken $NGROK_AUTH_TOKEN
        ./ngrok tcp --region=in 3389
