name: Web Terminal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
        unzip ngrok.zip
        
    - name: Authenticate with ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: Install dependencies
      run: sudo apt-get install -y wget
      
    - name: Install ttyd
      run: |
        wget https://github.com/tsl0922/ttyd/releases/download/1.6.3/ttyd.x86_64 -O ttyd
        chmod +x ttyd
        
    - name: Start ttyd session
      run: ./ttyd bash
      
    - name: Create ngrok tunnel
      run: ./ngrok http 7681
