            - name: Setup Minecraft
  # You may pin to the exact commit or the version.
  # uses: mcenv/setup-minecraft@2d092242881552b8ee463d9b4687bd38ef58a396
  uses: mcenv/setup-minecraft@v3.3.2
  with:
    # Minecraft version to use
    version: # optional, default is release
    # Whether to install Minecraft
    install: # optional, default is true
    # Whether to cache Minecraft
    cache: # optional
    # Number of retries to download Minecraft
    retries: # optional, default is 3
          
