name: PufferPanel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install any dependencies required for PufferPanel setup

      - name: Download Ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Authenticate Ngrok
        run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok
        run: ./ngrok http 8080 -log=stdout & ./ngrok tcp 5657 -log=stdout &

      - name: Start PufferPanel
        run: |
          # Start PufferPanel with SFTP configured to listen on port 5657
          # Example command: pufferpanel --port 5657 start

      # Add more steps as needed, such as running tests or deploying code
